name: echidna_server
description: "A software licensing server written in dart"
version: 1.1.0
repository: https://github.com/necodeIT/echidna_server
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  analyzer: any
  bloc: ^8.1.4
  collection: ^1.18.0
  crypto: ^3.0.6
  dotenv: ^4.2.0
  echidna_dto:
    git:
      url: https://github.com/necodeIT/echidna_dto.git
  either_dart: ^1.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logging: ^1.2.0
  mcquenji_core:
    git:
      url: https://github.com/mcquenji/mcquenji_core.git
  modular_test: ^2.0.0
  orm: ^5.2.0
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_docker_shutdown: ^1.1.0
  shelf_modular: ^2.1.0
  uuid: any

dependency_overrides:
  modular_core:
    git:
      url: https://github.com/necodeIT/modular.git
      path: modular_core
  shelf_modular:
    git:
      url: https://github.com/necodeIT/modular.git
      path: shelf_modular
  # echidna_dto:
  #   path: ../echidna_dto
dev_dependencies:
  architecture_linter: ^0.2.2
  build_runner: ^2.4.11
  coverage: ^1.10.0
  flutter_lints: ^3.0.0
  flutterando_analysis: ^0.0.2
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  test: ^1.25.2
