name: license_server
description: "A software licensing server written in dart"
version: 0.0.1
repository: https://github.com/necodeIT/license_server
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  collection: ^1.18.0
  either_dart: ^1.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logging: ^1.2.0
  mcquenji_core:
    git:
      url: https://github.com/mcquenji/mcquenji_core.git
  orm: ^5.2.0
  shelf: ^1.4.2
  shelf_modular: ^2.1.0

dependency_overrides:
  modular_core:
    git:
      url: git@github.com:necodeIT/modular.git
      path: modular_core
  shelf_modular:
    git:
      url: git@github.com:necodeIT/modular.git
      path: shelf_modular

dev_dependencies:
  architecture_linter: ^0.2.2
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutterando_analysis: ^0.0.2
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  test: ^1.25.2
