import 'package:shelf/shelf.dart';
import 'package:shelf_modular/shelf_modular.dart';

/// Adds a new Customer to the DB with and returns the new Customer with the id generated by the DB.
Future<Response> addCustomerHandler(Request request, Injector i, ModularArguments args) async {
  return Response.ok('Hello, World!');
}
