import 'package:license_server/license_server.dart';
import 'package:logging/logging.dart';
import 'package:orm/orm.dart';
import 'package:shelf/shelf.dart';
import 'package:shelf_modular/shelf_modular.dart';

/// Adds a new Customer to the DB with and returns the new Customer with the id generated by the DB.
Future<Response> addCustomerHandler(Request request, Injector i, ModularArguments args) async {
  final prisma = i.get<PrismaClient>();

  final name = args.data['name'] as String?;
  final email = args.data['email'] as String?;

  if (name == null || email == null) {
    return Response.badRequest(body: 'Customer name and email are required.');
  }

  try {
    await prisma.$transaction(
      (prisma) => prisma.customer.create(
        data: PrismaUnion.$1(
          CustomerCreateInput(
            name: name,
            email: email,
          ),
        ),
      ),
      isolationLevel: TransactionIsolationLevel.serializable,
    );
  } on Exception catch (e, s) {
    Logger('${request.method} ${request.url}').severe('Failed to add customer', e, s);
    return Response.internalServerError();
  }

  return Response.ok('Hello, World!');
}
